service: orderbook-importer

frameworkVersion: '2'
provider:
  name: aws
  stage: prod
  runtime: python3.7
  region: us-west-2
  timeout: 900
  iamRoleStatements:
    # Iam roles go here

functions:
  orderbook-importer:
    handler: handler.handler
    events: 
      - schedule: rate(1 day)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false

package:
  exclude:
    - venv/**
    - node_modules/**
